---
#
# For reference, create the install-config file by running
#
#   ./openshift-install create install-config --dir <installation_directory>

- name: Playbooks to provision a new cluster in AWS using the IPI method
  hosts: "{{ hostlist | default('all') }}"
  gather_facts: false
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_ocp_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_ocp_secret_access_key }}"
  vars:
    ocp_installer: "~/bin/openshift-install"

  tasks:
    - name: Check that mandatory variables are defined
      ansible.builtin.assert:
        fail_msg: |+
          The following variables must be defined (examples provided):
            ocp_bastion_node: "bastion.example.com"
            ocp_baseDomain: "example.com"
            ocp_computenode_replicas: "3"
            ocp_controlPlane_replicas: "3"
            ocp_clustername: "mynewocpcluster"
            ocp_aws_region: "us-east-1"
            ocp_pullSecret: "my-pull-secret"
            ocp_sshKey: "my-public-ssh-key"
            ocp_clusterinfo_dir: "./"
            aws_ocp_access_key_id: "your AWS_ACCESS_KEY_ID"
            aws_ocp_secret_access_key: "your AWS_SECRET_ACCESS_KEY"
        that:
          - ocp_bastion_node is defined
          - ocp_baseDomain is defined
          - ocp_computenode_replicas is defined
          - ocp_controlPlane_replicas is defined
          - ocp_clustername is defined
          - ocp_aws_region is defined
          - ocp_pullSecret is defined
          - ocp_sshKey is defined
          - ocp_clusterinfo_dir is defined
          - aws_ocp_access_key_id: "your AWS_ACCESS_KEY_ID"
          - aws_ocp_secret_access_key: "your AWS_SECRET_ACCESS_KEY"

    - name: Block to provision the cluster from the bastion node
      block:

        - name: Check the status of the OpenShift installer
          ansible.builtin.stat:
            path: "{{ ocp_installer }}"
          register: installer_stat

        - name: Print installer_stat
          debug:
            var: installer_stat
            verbosity: 1

        - name: Verify the OpenShift installer is present
          ansible.builtin.assert:
            fail_msg: "The OpenShift installer must be available at {{ ocp_installer }}"
            that:
              - installer_stat.stat.exists

        - name: Print cluster information
          ansible.builtin.debug:
            msg: "Creating cluster {{ ocp_clustername }}.{{ ocp_baseDomain }}"

        - name: Print inventory hostname
          ansible.builtin.debug:
            msg: "Inventory hostname {{ inventory_hostname }}"

        - name: Ensure the base directory holding the cluster provisioning information is created
          ansible.builtin.file:
            path: "{{ ocp_clusterinfo_dir }}"
            state: "directory"

        - name: Ensure the config directory is created
          ansible.builtin.file:
            path: "{{ ocp_clusterinfo_dir }}/config"
            state: "directory"

        - name: Ensure the install-config.yaml file is created
          ansible.builtin.template:
            dest: "{{ ocp_clusterinfo_dir }}/config/install-config.yaml"
            src: "install-config.yaml.j2"

        - name: Ensure the AWS key is reflected
          ansible.builtin.command:
            chdir: "{{ ocp_clusterinfo_dir }}"
            cmd: "echo ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}"
          register: aws_key_output

        - name: Print AWS key info
          ansible.builtin.debug:
            var: aws_key_output
            verbosity: 1

        - name: Command to run
          ansible.builtin.debug:
            msg: "{{ ocp_installer }} create cluster --dir {{ ocp_clusterinfo_dir }}/config --log-level=info"

        - name: Create the cluster
          ansible.builtin.command:
            chdir: "{{ ocp_clusterinfo_dir }}"
            cmd: "{{ ocp_installer }} create cluster --dir {{ ocp_clusterinfo_dir }}/config --log-level=info"

        - name: Get the kubeadmin password
          ansible.builtin.slurp:
            src: "{{ ocp_clusterinfo_dir }}/config/auth/kubeadmin-password"
          register: kubeadmin_pw

        - name: Print connection information
          ansible.builtin.debug:
            msg:
              - "Web console:  https://console-openshift-console.apps.{{ ocp_clustername }}.{{ ocp_baseDomain }}"
              - "Username   :  kubeadmin"
              - "Password   :  {{ kubeadmin_pw.content | b64decode }}"
              - "API        :  https://api.{{ ocp_clustername }}.{{ ocp_baseDomain }}:6443"

      delegate_to: "{{ ocp_bastion_node }}"
