---
# Work in progress - testing with SNOW
- name: Playbooks to provision a new cluster in AWS using the IPI method
  hosts: "{{ hostlist | default('all') }}"
  vars:
    ocp_baseDomain: "example.com"
    ocp_computenode_replicas: "3"
    ocp_controlPlane_replicas: "3"
    ocp_clustername: "mynewocpcluster"
    ocp_aws_region: "us-east-1"
    ocp_pullSecret: "my-pull-secret"
    ocp_sshKey: "my-public-ssh-key"
    ocp_clusterinfo_dir: "./"
  environment:
    AWS_ACCESS_KEY_ID: "my-aws-access-key"
    AWS_SECRET_ACCESS_KEY: "my-aws-secret-access-key"

  tasks:
    - name: Print cluster information
      ansible.builtin.debug:
        msg: "Creating cluster {{ ocp_clustername }}.{{ ocp_baseDomain }}"

    - name: Ensure the directory for the install-config.yaml file is created
      ansible.builtin.file:
        path: "{{ ocp_clusterinfo_dir }}"
        state: "directory"

    - name: Ensure the base directory holding the cluster provisioning information is created
      ansible.builtin.file:
        path: "{{ ocp_clusterinfo_dir }}/config"
        state: "directory"

    - name: Ensure the install-config.yaml file is created
      ansible.builtin.template:
        dest: "{{ ocp_clusterinfo_dir }}/install-config.yaml"
        src: "install-config.yaml.j2"

# To do
#    - name: Install the cluster
